### ISSUE TITLE
How to access your paper?

### ISSUE THREAD

**Issue by qilong-zhang** [ZhengyuZhao/Targeted-Tansfer#1]
Hi, the link in your `readme` is not available, and I cannot search your paper too, so how to get your paper

**Comment by machanic** [comment]
论文链接给错了，你在README链接给出的论文是Towards Large yet Imperceptible Adversarial Image Perturbations with Perceptual Color Distance，而非Zhengyu Zhao, Zhuoran Liu, Martha Larson, "On Success and Simplicity: A Second Look at Transferable Targeted Attacks", 2020.

**Comment by ZhengyuZhao** [comment]
> Hi, the link in your `readme` is not available, and I cannot search your paper too, so how to get your paper

Thanks for your interest. Yes, the link in the readme was just a placeholder. Now I have got the permanent arXiv link for our paper and updated the readme.

**Comment by ZhengyuZhao** [comment]
> 论文链接给错了，你在README链接给出的论文是Towards Large yet Imperceptible Adversarial Image Perturbations with Perceptual Color Distance，而非Zhengyu Zhao, Zhuoran Liu, Martha Larson, "On Success and Simplicity: A Second Look at Transferable Targeted Attacks", 2020.

Thanks! It is correct now.
