### ISSUE TITLE
[Help] Dataset Download Problem

### ISSUE THREAD

**Issue by datong-new** [ZhengyuZhao/Targeted-Tansfer#3]
Hello, thanks for your work!

I have trouble downloading the dataset because some image URLs are invalid. I can only download 911 images rather than 1000.

So could you help share the original images? Thanks!

**Comment by ZhengyuZhao** [comment]
> Hello, thanks for your work!
> 
> I have trouble downloading the dataset because some image URLs are invalid. I can only download 911 images rather than 1000.
> 
> So could you help share the original images? Thanks!

Thanks for your interest! I just provide the original 1000 images with the required size of 299x299 in the folder "dataset/images". Enjoy!

**Comment by datong-new** [comment]
> Thanks for your interest! I just provide the original 1000 images with the required size of 299x299 in the folder "dataset/images". Enjoy!

I appreciate your kind help very much! Much thanks!

**Comment by ZhengyuZhao** [comment]
> > Thanks for your interest! I just provide the original 1000 images with the required size of 299x299 in the folder "dataset/images". Enjoy!
> 
> I appreciate your kind help very much! Much thanks!

You're welcome!
