### ISSUE TITLE
The list of images may not match with list of labels.

### ISSUE THREAD

**Issue by datong-new** [ZhengyuZhao/Targeted-Tansfer#4]
Hello, the code in your jupyter has two `image_id_list `, `image_id_list = list(filter(lambda x: '.png' in x, os.listdir(input_path)))` and `image_id_list,label_ori_list,label_tar_list=load_ground_truth(os.path.join('../', 'images.csv'))` may be in different order. 

And the final `image_id_list ` may not match the label order.

![image](https://user-images.githubusercontent.com/22614443/106225567-62bd9800-6220-11eb-80d9-d645035d6d9c.png)

**Comment by ZhengyuZhao** [comment]
> Hello, the code in your jupyter has two `image_id_list `, `image_id_list = list(filter(lambda x: '.png' in x, os.listdir(input_path)))` and `image_id_list,label_ori_list,label_tar_list=load_ground_truth(os.path.join('../', 'images.csv'))` may be in different order.
> 
> And the final `image_id_list ` may not match the label order.
> 
> ![image](https://user-images.githubusercontent.com/22614443/106225567-62bd9800-6220-11eb-80d9-d645035d6d9c.png)

Thanks for pointing out this issue. I will check my local code to see if there is also such an issue and then update the code asap.

**Comment by ZhengyuZhao** [comment]
I have fixed the issue, and the new results are generally a little lower than before for all methods.
The updated paper will be available asap.
